services:
  - type: web
    name: itm-assignment-09-pharmacy-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MONGO_URI
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1d
